version: '3'
services:
  docker-mysql:
    image: mysql:latest
    container_name: docker-mysql
    environment:
      MYSQL_ROOT_PASSWORD : pass
      MYSQL_DATABASE : EmpDB
      MYSQL_PASSWORD : pass
    ports:
      - 3307:3306
#     volumes:
#       - mysql-volume:/var/lib/mysql
    networks:
      - app-network
  myapp:
    image: mangesh98/myapp:latest
    container_name: myapp
    ports:
       - 8888:8888
#     build:
#       context : ./employee-management/
#       dockerfile : Dockerfile
    environment:
      SPRING_APPLICATION_JSON: '{"eureka":{"client":{"serviceUrl":{"defaultZone":"http://eureka-server:8761/eureka"}}}}'
    depends_on:
      - eureka-server
      - config-server
      - docker-mysql
    restart : on-failure
    networks:
      - app-network
  eureka-server:
    image: mangesh98/eureka:latest
    container_name: eureka-server
    ports:
      - 8761:8761
#     build:
#       context: ./eureka-server/
#       dockerfile : Dockerfile
    restart : on-failure
    networks:
      - app-network
  node:
    image: mangesh98/mynode:latest
    container_name: node
    ports:
      - 3000:3000
#     build:
#       context : ./Node/
#       dockerfile : Dockerfile
    depends_on:
      - myapp
    networks:
      - app-network
    restart : on-failure
  config-server:
    image : mangesh98/config-server:latest
    container_name: config-server
    ports:
      - 8191:8191
#     build:
#       context: ./config-server/
#       dockerfile : Dockerfile
    networks:
        - app-network
networks:
  app-network:
    driver : bridge
# volumes:
#   mysql-volume:
#     name : mysql-volume
#     external : true
